import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/global/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{ fontFamily: "Whisper, Ortank, sans-serif" }}
      >
        <Navigation />
        <div className="relative z-20 w-screen min-h-screen">{children}</div>
      </body>
    </html>
  );
}
