import type { SpecimenTemplate } from "./schema";

/**
 * Predefined specimen page templates with varied layouts and styles
 */
export const SPECIMEN_TEMPLATES: SpecimenTemplate[] = [
  {
    title: "Classic Grid",
    backgroundType: "color",
    description:
      "A traditional 2×2 grid layout with balanced spacing",
    backgroundColor: "#ffffff",
    fontColor: "#1a1a1a",
    margin: [24, 32, 24, 32],
    grid: { columns: 2, rows: 2, gap: 16 },
    cells: [
      {
        uuid: "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "**A**",
      },
      {
        uuid: "b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "**B**",
      },
      {
        uuid: "c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "**C**",
      },
      {
        uuid: "d4e5f6a7-b8c9-7d8e-1f2a-3b4c5d6e7f8a",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "**D**",
      },
    ],
  },
  {
    title: "Warm Gradient",
    backgroundType: "color",
    description:
      "Soft warm tones with a 3×2 layout for more content",
    backgroundColor: "#faf6f0",
    fontColor: "#2d2a26",
    margin: [40, 48, 40, 48],
    grid: { columns: 3, rows: 2, gap: 24 },
    cells: [
      {
        uuid: "e5f6a7b8-c9d0-8e9f-2a3b-4c5d6e7f8a9b",
        colSpan: 2,
        rowSpan: 1,
        padding: [24, 24, 24, 24],
        background: "#fff8f0",
        fontColor: "#1a1612",
        textAlign: "left",
        verticalAlign: "top",
        content: "## Specimen",
      },
      {
        uuid: "f6a7b8c9-d0e1-9f0a-3b4c-5d6e7f8a9b0c",
        colSpan: 1,
        rowSpan: 1,
        padding: [24, 24, 24, 24],
        background: null,
        fontColor: null,
        textAlign: "right",
        verticalAlign: "center",
        content: "Aa",
      },
      {
        uuid: "a7b8c9d0-e1f2-0a1b-4c5d-6e7f8a9b0c1d",
        colSpan: 3,
        rowSpan: 1,
        padding: [32, 32, 32, 32],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "Type here...",
      },
    ],
  },
  {
    title: "Minimal Dark",
    backgroundType: "color",
    description:
      "Dark background with high contrast for display specimens",
    backgroundColor: "#1a1a1a",
    fontColor: "#f5f5f5",
    margin: [32, 40, 32, 40],
    grid: { columns: 2, rows: 3, gap: 12 },
    cells: [
      {
        uuid: "b8c9d0e1-f2a3-1b2c-5d6e-7f8a9b0c1d2e",
        colSpan: 2,
        rowSpan: 1,
        padding: [20, 20, 20, 20],
        background: "#2a2a2a",
        fontColor: "#ffffff",
        textAlign: "center",
        verticalAlign: "center",
        content: "**Display**",
      },
      {
        uuid: "c9d0e1f2-a3b4-2c3d-6e7f-8a9b0c1d2e3f",
        colSpan: 1,
        rowSpan: 2,
        padding: [20, 20, 20, 20],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "top",
        content: "Body text",
      },
      {
        uuid: "d0e1f2a3-b4c5-3d4e-7f8a-9b0c1d2e3f4a",
        colSpan: 1,
        rowSpan: 2,
        padding: [20, 20, 20, 20],
        background: null,
        fontColor: null,
        textAlign: "right",
        verticalAlign: "bottom",
        content: "Numbers 0123456789",
      },
    ],
  },
  {
    title: "Editorial",
    backgroundType: "color",
    description:
      "Asymmetric layout inspired by editorial design",
    backgroundColor: "#f8f8f8",
    fontColor: "#111111",
    margin: [48, 56, 48, 56],
    grid: { columns: 4, rows: 2, gap: 20 },
    cells: [
      {
        uuid: "e1f2a3b4-c5d6-4e5f-8a9b-0c1d2e3f4a5b",
        colSpan: 1,
        rowSpan: 2,
        padding: [16, 16, 16, 16],
        background: "#e8e4e0",
        fontColor: "#333333",
        textAlign: "center",
        verticalAlign: "center",
        content: "A",
      },
      {
        uuid: "f2a3b4c5-d6e7-5f6a-9b0c-1d2e3f4a5b6c",
        colSpan: 3,
        rowSpan: 1,
        padding: [24, 24, 24, 24],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "center",
        content: "## Title",
      },
      {
        uuid: "a3b4c5d6-e7f8-6a7b-0c1d-2e3f4a5b6c7d",
        colSpan: 3,
        rowSpan: 1,
        padding: [24, 24, 24, 24],
        background: null,
        fontColor: null,
        textAlign: "justify",
        verticalAlign: "top",
        content: "Specimen sample text.",
      },
    ],
  },
  {
    title: "Wide Header",
    backgroundType: "gradient",
    gradient: { from: "#667eea", to: "#764ba2" },
    description:
      "Full-width header spanning 3 columns with 2×2 content below",
    backgroundColor: "#f0f0f0",
    fontColor: "#2d2d2d",
    margin: [20, 24, 20, 24],
    grid: { columns: 3, rows: 3, gap: 12 },
    cells: [
      {
        uuid: "wide-header-1",
        colSpan: 3,
        rowSpan: 1,
        padding: [24, 24, 24, 24],
        background: "#5a67d8",
        fontColor: "#ffffff",
        textAlign: "center",
        verticalAlign: "center",
        content: "## Title",
      },
      {
        uuid: "wide-header-2",
        colSpan: 2,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "top",
        content: "Body",
      },
      {
        uuid: "wide-header-3",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: "#e2e8f0",
        fontColor: "#1a202c",
        textAlign: "center",
        verticalAlign: "center",
        content: "Side",
      },
      {
        uuid: "wide-header-4",
        colSpan: 3,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "Footer",
      },
    ],
  },
  {
    title: "Tall Sidebar",
    backgroundType: "color",
    description: "Sidebar spanning 3 rows on the left",
    backgroundColor: "#ffffff",
    fontColor: "#1a1a1a",
    margin: [24, 32, 24, 32],
    grid: { columns: 3, rows: 4, gap: 16 },
    cells: [
      {
        uuid: "tall-sidebar-1",
        colSpan: 1,
        rowSpan: 3,
        padding: [20, 20, 20, 20],
        background: "#edf2f7",
        fontColor: "#2d3748",
        textAlign: "center",
        verticalAlign: "center",
        content: "Nav",
      },
      {
        uuid: "tall-sidebar-2",
        colSpan: 2,
        rowSpan: 1,
        padding: [20, 20, 20, 20],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "top",
        content: "## Header",
      },
      {
        uuid: "tall-sidebar-3",
        colSpan: 2,
        rowSpan: 2,
        padding: [20, 20, 20, 20],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "top",
        content: "Content",
      },
      {
        uuid: "tall-sidebar-4",
        colSpan: 3,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "Footer",
      },
    ],
  },
  {
    title: "Magazine",
    backgroundType: "gradient",
    gradient: { from: "#fdfbfb", to: "#ebedee" },
    description:
      "Large featured cell spanning 2×2 with supporting cells",
    backgroundColor: "#ffffff",
    fontColor: "#1a1a1a",
    margin: [32, 40, 32, 40],
    grid: { columns: 3, rows: 3, gap: 20 },
    cells: [
      {
        uuid: "magazine-1",
        colSpan: 2,
        rowSpan: 2,
        padding: [32, 32, 32, 32],
        background: "#2c3e50",
        fontColor: "#ecf0f1",
        textAlign: "center",
        verticalAlign: "center",
        content: "## Feature",
      },
      {
        uuid: "magazine-2",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "right",
        verticalAlign: "top",
        content: "Aa",
      },
      {
        uuid: "magazine-3",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: "#ecf0f1",
        fontColor: "#2c3e50",
        textAlign: "left",
        verticalAlign: "top",
        content: "Caption",
      },
      {
        uuid: "magazine-4",
        colSpan: 3,
        rowSpan: 1,
        padding: [20, 20, 20, 20],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "center",
        content: "Supporting text",
      },
    ],
  },
  {
    title: "Dashboard",
    backgroundType: "color",
    description: "4×4 grid with multiple spanning cells",
    backgroundColor: "#1a202c",
    fontColor: "#e2e8f0",
    margin: [24, 24, 24, 24],
    grid: { columns: 4, rows: 4, gap: 12 },
    cells: [
      {
        uuid: "dashboard-1",
        colSpan: 2,
        rowSpan: 2,
        padding: [20, 20, 20, 20],
        background: "#2d3748",
        fontColor: "#ffffff",
        textAlign: "center",
        verticalAlign: "center",
        content: "## Main",
      },
      {
        uuid: "dashboard-2",
        colSpan: 2,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: "#4a5568",
        fontColor: "#e2e8f0",
        textAlign: "center",
        verticalAlign: "center",
        content: "Stats",
      },
      {
        uuid: "dashboard-3",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "1",
      },
      {
        uuid: "dashboard-4",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "2",
      },
      {
        uuid: "dashboard-5",
        colSpan: 2,
        rowSpan: 2,
        padding: [20, 20, 20, 20],
        background: "#2d3748",
        fontColor: "#e2e8f0",
        textAlign: "left",
        verticalAlign: "top",
        content: "## Side",
      },
      {
        uuid: "dashboard-6",
        colSpan: 2,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "left",
        verticalAlign: "center",
        content: "Row",
      },
      {
        uuid: "dashboard-7",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "A",
      },
      {
        uuid: "dashboard-8",
        colSpan: 1,
        rowSpan: 1,
        padding: [16, 16, 16, 16],
        background: null,
        fontColor: null,
        textAlign: "center",
        verticalAlign: "center",
        content: "B",
      },
    ],
  },
];

const TEMPLATE_GRADIENTS: Record<number, string> = {
  0: "linear-gradient(135deg, #e8e8e8 0%, #f5f5f5 50%, #ffffff 100%)",
  1: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)",
  2: "linear-gradient(135deg, #2c3e50 0%, #1a1a2e 50%, #16213e 100%)",
  3: "linear-gradient(135deg, #a8edea 0%, #fed6e3 50%, #d4a5f3 100%)",
  4: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  5: "linear-gradient(135deg, #edf2f7 0%, #e2e8f0 100%)",
  6: "linear-gradient(135deg, #2c3e50 0%, #3498db 100%)",
  7: "linear-gradient(135deg, #1a202c 0%, #4a5568 100%)",
};

export function getTemplateGradient(
  templateTitle: string
): string {
  const index = SPECIMEN_TEMPLATES.findIndex(
    (t) => t.title === templateTitle
  );
  return TEMPLATE_GRADIENTS[index] ?? TEMPLATE_GRADIENTS[0];
}

export function getTemplateByTitle(
  title: string
): SpecimenTemplate | undefined {
  return SPECIMEN_TEMPLATES.find((t) => t.title === title);
}
