import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Register a font that supports Korean characters
Font.register({
  family: "NotoSansKR",
  fonts: [
    {
      src: "https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-kr@latest/korean-400-normal.ttf",
      fontWeight: 400,
    },
    {
      src: "https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-kr@latest/korean-700-normal.ttf",
      fontWeight: 700,
    },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: "NotoSansKR",
    fontSize: 10,
    lineHeight: 1.6,
    color: "#1a1a1a",
  },
  header: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 20,
    textAlign: "center",
  },
  paragraph: {
    marginBottom: 8,
    textAlign: "justify",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

export function EulaPdfDocument({
  eulaText,
}: {
  eulaText: string;
}) {
  // Split text into lines, preserving paragraph structure
  const lines = eulaText.split("\n");

  // Group consecutive non-empty lines into paragraphs
  const paragraphs: string[] = [];
  let current = "";
  for (const line of lines) {
    if (line.trim() === "") {
      if (current) {
        paragraphs.push(current.trim());
        current = "";
      }
      paragraphs.push(""); // preserve empty line as spacing
    } else {
      current += (current ? "\n" : "") + line;
    }
  }
  if (current) {
    paragraphs.push(current.trim());
  }

  return (
    <Document>
      <Page
        size="A4"
        style={styles.page}
      >
        {paragraphs.map((paragraph, index) => {
          if (paragraph === "") {
            return (
              <View
                key={index}
                style={{ marginBottom: 6 }}
              />
            );
          }

          // Detect heading-like lines (e.g., "제1조" or all-caps lines)
          const isHeading =
            /^제\d+조/.test(paragraph) ||
            /^Article\s+\d+/i.test(paragraph) ||
            /^[A-Z\s]{10,}$/.test(paragraph);

          const headingStyle = isHeading
            ? {
                fontWeight: 700 as const,
                fontSize: 11,
                marginTop: 12,
                marginBottom: 4,
              }
            : {};

          return (
            <Text
              key={index}
              style={[styles.paragraph, headingStyle]}
            >
              {paragraph}
            </Text>
          );
        })}

        <Text
          style={styles.footer}
          fixed
        >
          Generated by Type Around Korean Community
        </Text>
      </Page>
    </Document>
  );
}
