const STUDIOS = [
  {
    id: "655ff073-cc90-48ff-a8c8-808e8418888d",
    name: "lo-ol Studio",
    description:
      "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "lo-ol Studio",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "lo-ol Studio",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "lo-ol Studio",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "lo-ol Studio",
      },
    ],
  },
  {
    id: "2297e6ff-4b7c-47d3-a7da-975863006012",
    name: "Minjoo Type",
    description:
      "Vivamus ut lacinia nunc quisque congue nibh lacinia enim velit.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Minjoo Type",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Minjoo Type",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Minjoo Type",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Minjoo Type",
      },
    ],
  },
  {
    id: "e83c73c5-42d0-40aa-aa5c-859a8c58c904",
    name: "Font Pia",
    description:
      "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Font Pia",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Font Pia",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Font Pia",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Font Pia",
      },
    ],
  },
  {
    id: "0ab4b7de-649b-44d5-b164-695de9435361",
    name: "Moa Design",
    description:
      "Vivamus ut lacinia nunc quisque congue nibh lacinia enim velit.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
    ],
  },
  {
    id: "8336194b-7272-4799-99cf-9a2de8d71b2d",
    name: "Mijin Letters",
    description:
      "Vivamus ut lacinia nunc quisque congue nibh lacinia enim velit.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
    ],
  },
  {
    id: "d77ce74f-45ce-4e65-b20f-1ccfda87e234",
    name: "Suyeong Han Studio",
    description:
      "Vivamus ut lacinia nunc quisque congue nibh lacinia enim velit.",
    gradient: ["#FFF8E8", "#F2F2F2"],
    image: "/mock/profile/studio_profile_01.png",
    website: "https://www.lo-ol.design",
    typefaces: [
      {
        name: "Giparan",
        slug: "giparan",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_giparan.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Arvana",
        slug: "arvana",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_arvana.svg",
        fonts: 12,
        characters: 1024,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
      {
        name: "Ortank",
        slug: "ortank",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_ortank.svg",
        fonts: 8,
        characters: 2800,
        releaseDate: "2024-01-01",
        category: ["sans-serif"],
        studio: "Moa Design",
      },
      {
        name: "Banya Mist",
        slug: "banya-mist",
        description:
          "Lorem ipsum dolor sit amet fermentum curabitur urna est luctus justo massa.",
        icon: "/mock/typefaces/icn_banya.svg",
        fonts: 8,
        characters: 1456,
        releaseDate: "2024-01-01",
        category: ["serif"],
        studio: "Moa Design",
      },
    ],
  },
];

export default STUDIOS;
